name: 'Welcome New Contributors'

permissions:
  issues: write
  pull-requests: write

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet the contributor'
        uses: garg3133/welcome-new-contributors@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Welcome! Join our Slack: [https://join.slack.com/t/opsimate/shared_invite/zt-39bq3x6et-NrVCZzH7xuBGIXmOjJM7gA](https://join.slack.com/t/opsimate/shared_invite/zt-39bq3x6et-NrVCZzH7xuBGIXmOjJM7gA)  
            Also, don't forget to star ⭐️ the repository if you find it helpful!
          pr-message: >
            Thanks for your contribution! Join our Slack: [https://join.slack.com/t/opsimate/shared_invite/zt-39bq3x6et-NrVCZzH7xuBGIXmOjJM7gA](https://join.slack.com/t/opsimate/shared_invite/zt-39bq3x6et-NrVCZzH7xuBGIXmOjJM7gA)  
            Please make sure to include an image with your PR — it really helps us review and understand the changes better.
            Only in rare cases will we accept a PR without one.
            Also, take a moment to review your code to ensure it’s clear, readable, and easy to follow.
            PRs from contributors who haven’t joined our Slack community or starred the repository won’t be reviewed — we’d love to see you join and be part of the project!